# Generated by Django 6.1.1 on 2026-09-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('headline', models.CharField(default='Full Stack Developer', max_length=255)),
                ('short_bio', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('about_text', models.TextField(blank=True)),
                ('about_image_url', models.URLField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('twitter_url', models.URLField(blank=True, max_length=500)),
                ('resume_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
