# Generated by Django 6.1.1 on 2026-09-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-issue_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('technologies', models.CharField(blank=True, help_text='Comma separated list', max_length=500)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Training',
                'ordering': ['-start_date', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('technologies', models.CharField(blank=True, help_text='Comma separated list', max_length=500)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
                'abstract': False,
            },
        ),
    ]
